# Book settings
title : "Coding for Data - 2021 edition"
author: Matthew Brett, Ani Adhikari, John Denero, David Wagner, Peter Rush
logo: images/dsfe_logo.png
email: matthew.brett@gmail.com
# >- starts a multiline string, where newlines replaced by spaces, and final
# newlines are stripped.
description: >-
  Textbook for some University of Birmingham Data Science modules.

execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: auto
  timeout: 120

exclude_patterns: [README.md, todo.md, _scripts]

html:
  favicon: images/dsfe_favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://uob-ds.github.io/cfd2021

repository:
  url: https://github.com/uob-ds/cfd2021
  branch: master

launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "classic"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
  # The URL of Google Colab (e.g., https://colab.research.google.com)
  colab_url: "https://colab.research.google.com"
  thebe: true

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]

    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd

  extra_extensions:
    # For noting license and linking to data8 version of page.
    - cfdcode.ucb_page
    # For documenting 'click' Python CLIs
    # - sphinx_click.ext
    # Directive for creating tab panels in pages.
    # https://github.com/djungelorm/sphinx-tabs
    # - sphinx_tabs.tabs
    # A sphinx extension for creating panels in a grid layout or as
    # drop-downs.
    # - sphinx_panels

latex:
  latex_documents:
    targetname: cfd2020.tex

bibtex_bibfiles:
  - _references.bib

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir : _build/html
  redirects:
    data-types/Ranges: ../arrays/Ranges
    data-types/Arrays: ../arrays/Arrays
    arrays-iteration/More_on_Arrays: ../arrays/More_on_Arrays
    arrays-iteration/array_indexing: ../arrays/array_indexing
    arrays-iteration/filling_arrays: ../arrays/filling_arrays
    data-types/function_arguments: ../arrays/function_arguments
    data-types/leaping_ahead: ../arrays/leaping_ahead
    arrays-iteration/arrays_and_axes: ../iteration/arrays_and_axes
    arrays-iteration/indentation: ../iteration/indentation
    arrays-iteration/iteration: ../iteration/iteration
    arrays-iteration/reply_supreme: ../iteration/reply_supreme

